
## Sean Elliott - April 2024
# 
# Simulate to get the cross-sectional inequality results from Bloom et al. 2024
# We want to show that within-firm inequality is greater for more productive firms
# Two scenarios
# 1. Inequality is generated by the revenue function (a > b)
# 2. Inequality is generated by the distribution (mu_k > mu_s)
# Import libraries

import sys, os

# Set working directory to be root directory of the repository

os.chdir(os.path.dirname(__file__))
os.chdir('../..')

# Import the "package"

sys.path.append("code/utilities")
import roy_model_matching as rmm

# Scenario 1

size = 1000
dist = "lognormal"
dist_params = {'mean_k': 0.5,'mean_s': 0.5,'variance': 1,'correlation': 0}

revenue_params = {'a':1,'b':0.25,'c':1,'n':2,'m':1,'cons':2}
scenario1 = rmm.model_sim(size,dist,dist_params,revenue_params,tolerance=0.001)

rmm.plot_ineq_cross_sect(scenario1,output_path = os.path.join(os.getcwd(),'docs', 'cs_ineq_sims','rev_func_ineq.png'))

# Scenario 2

size = 1000
dist = "lognormal"
dist_params = {'mean_k': 1,'mean_s': -1,'variance': 1,'correlation': 0}

revenue_params = {'a':0.5,'b':0.5,'c':0.15,'n':1,'m':1,'cons':2}
scenario2 = rmm.model_sim(size,dist,dist_params,revenue_params,tolerance=0.001)

rmm.plot_ineq_cross_sect(scenario2,output_path = os.path.join(os.getcwd(),'docs', 'cs_ineq_sims','skill_dist_ineq_neg.png'))

# Scenario 3

size = 1000
dist = "lognormal"
dist_params = {'mean_k': -1,'mean_s': 1,'variance': 1,'correlation': 0}

revenue_params = {'a':0.5,'b':0.5,'c':0.15,'n':1,'m':1,'cons':2}
scenario3 = rmm.model_sim(size,dist,dist_params,revenue_params,tolerance=0.001)

rmm.plot_ineq_cross_sect(scenario3,output_path = os.path.join(os.getcwd(),'docs', 'cs_ineq_sims','skill_dist_ineq_pos.png'))